"""Concept catalog for label-driven IPEDS harmonization.

This module exposes the ``CONCEPTS`` dictionary used by ``harmonize_new`` to
identify and extract concept-aligned variables from IPEDS survey files. The
catalog replaces CSV crosswalks with an in-repo Python source of truth. Each
concept entry specifies its descriptive metadata, acceptable forms, matching
patterns, and transform hints.

The harmonizer consumes this catalog to drive label-based resolution against the
``dictionary_lake.parquet`` generated by ``01_ingest_dictionaries.py``. When
``download_ipeds.py`` refreshes yearly manifests, ``harmonize_new`` can combine
those manifests with the concept catalog to locate and parse the correct survey
files without editing legacy modules.
"""

from __future__ import annotations

from collections import OrderedDict


CONCEPTS: "OrderedDict[str, dict[str, object]]" = OrderedDict(
    {
        # -------------------------
        # Finance (FY, aligned forms)
        # -------------------------
        "total_rev_invest_return": {
            "target_var": "total_rev_invest_return",
            "concept": "Total revenues and investment return (aligned forms)",
            "units": "USD",
            "survey": "Finance",
            "period_type": "FY",
            "forms": ["F1A", "F2A", "F3A"],
            "label_regex": [
                r"^total revenues?(?: and (?:other additions )?)?investment (?:return|income).*$",
                r"^total revenues?(?:,? operating and nonoperating)?.*investment (?:return|income).*$",
            ],
            "exclude_regex": [
                r"endowment (?:market )?value",
                r"balance sheet|net assets|position",
            ],
            "notes": "Aligned total. Avoid stock accounts and balance-sheet lines.",
            "transform": "identity",
        },
        "tuition_fees_net": {
            "target_var": "tuition_fees_net",
            "concept": "Tuition and fees revenue, net of discounts/allowances",
            "units": "USD",
            "survey": "Finance",
            "period_type": "FY",
            "forms": ["F1A", "F2A", "F3A"],
            "label_regex": [
                r"^tuition(?: and)? fees.*after deducting (?:discounts|scholarship allowances)",
                r"^tuition(?: and)? fees.*\(net\)$",
                r"^net tuition(?: and)? fees$",
            ],
            "exclude_regex": [
                r"\bgross\b",
                r"before deducting",
                r"discounts? and allowances$",
                r"scholarship allowances$",
            ],
            "notes": "Map only the net line. Exclude allowances and gross.",
            "transform": "identity",
        },
        "state_appropriations": {
            "target_var": "state_appropriations",
            "concept": "State appropriations",
            "units": "USD",
            "survey": "Finance",
            "period_type": "FY",
            "forms": ["F1A", "F2A"],
            "label_regex": [
                r"^state appropriations(?:,? (?:operating|nonoperating))?$",
                r"^state appropriations$",
            ],
            "exclude_regex": [],
            "notes": "Typically not present for for-profits.",
            "transform": "identity",
        },
        "investment_return": {
            "target_var": "investment_return",
            "concept": "Investment return (income, gains, losses)",
            "units": "USD",
            "survey": "Finance",
            "period_type": "FY",
            "forms": ["F1A", "F2A", "F3A"],
            "label_regex": [
                r"^investment return(?:.*)$",
                r"^investment income(?:.*)$",
                r"^net investment (?:income|return)(?:.*)$",
            ],
            "exclude_regex": [
                r"endowment (?:market )?value",
            ],
            "notes": "Flow item; not the endowment stock.",
            "transform": "identity",
        },
        "auxiliary_rev": {
            "target_var": "auxiliary_rev",
            "concept": "Auxiliary enterprises revenue",
            "units": "USD",
            "survey": "Finance",
            "period_type": "FY",
            "forms": ["F1A", "F2A", "F3A"],
            "label_regex": [
                r"^auxiliary (?:enterprise|enterprises) revenues?$",
                r"^sales and services of auxiliary enterprises$",
            ],
            "exclude_regex": [
                r"expenses?",
            ],
            "notes": "Revenue only; not auxiliary expenses.",
            "transform": "identity",
        },
        "total_expenses": {
            "target_var": "total_expenses",
            "concept": "Total expenses (aligned forms)",
            "units": "USD",
            "survey": "Finance",
            "period_type": "FY",
            "forms": ["F1A", "F2A", "F3A"],
            "label_regex": [
                r"^total expenses?(?: and deductions)?$",
                r"^total expenses?$",
            ],
            "exclude_regex": [],
            "notes": "",
            "transform": "identity",
        },
        "instruction_exp": {
            "target_var": "instruction_exp",
            "concept": "Instruction expenses",
            "units": "USD",
            "survey": "Finance",
            "period_type": "FY",
            "forms": ["F1A", "F2A", "F3A"],
            "label_regex": [
                r"^instruction(?:\s*expenses?)?$",
                r"^instruction\s*-\s*total$",
            ],
            "exclude_regex": [
                r"instructional support",
            ],
            "notes": "Functional expense.",
            "transform": "identity",
        },

        # -------------------------
        # Enrollment (AY)
        # -------------------------
        "ef_total": {
            "target_var": "ef_total",
            "concept": "Total fall headcount",
            "units": "count",
            "survey": "FallEnrollment",
            "period_type": "AY",
            "forms": ["EF"],
            "label_regex": [
                r"^grand total$",
                r"^all students total$",
                r"^total enrollment$",
                r"^total$",
            ],
            "exclude_regex": [
                r"undergraduate|graduate",
                r"\bmen\b|\bwomen\b|\bmale\b|\bfemale\b",
                r"nonresident|unknown",
                r"part[- ]?time|full[- ]?time",
                r"by race|ethnicity|age|level|resident|attendance",
            ],
            "notes": "Fall snapshot grand total only.",
            "transform": "identity",
        },
        "e12_fte": {
            "target_var": "e12_fte",
            "concept": "12-month FTE (NCES rule)",
            "units": "FTE",
            "survey": "12MonthEnrollment",
            "period_type": "AY",
            "forms": ["E12", "E1D", "EFFY"],
            "label_regex": [
                r"(?:^|.*)\b12[- ]?month\b.*\bfull[- ]?time equivalent\b.*",
                r"(?:^|.*)\bfull[- ]?time equivalent\b.*\b12[- ]?month\b.*",
                r"(?:^|.*)\beffy\b.*\bfull[- ]?time equivalent\b.*",
            ],
            "exclude_regex": [
                r"\bfall\b",
                r"\bef\b",
                r"\bundergraduate\b|\bgraduate\b",
            ],
            "notes": "Use E12/E1D/EFFY derived FTE; avoid EF fall FTE variants.",
            "transform": "identity",
        },

        # -------------------------
        # SFA (AY)
        # -------------------------
        "pell_recip_count": {
            "target_var": "pell_recip_count",
            "concept": "Pell Grant recipients (FTFT undergraduates)",
            "units": "count",
            "survey": "StudentFinancialAid",
            "period_type": "AY",
            "forms": ["SFA"],
            "label_regex": [
                r"(?:^|.*)\b(number|no\.)\s+of\b.*\bpell\b.*\bfull[- ]?time\b.*\bfirst[- ]?time\b.*\bundergrad",
                r"(?:^|.*)\bpell\b.*\brecipients?\b.*\bfull[- ]?time\b.*\bfirst[- ]?time\b",
            ],
            "exclude_regex": [
                r"\bamount\b|\bdollar(s)?\b|\bavg\b|\baverage\b|\bper[- ]?recipient\b|\btotal amount\b",
            ],
            "notes": "Restrict to FTFT cohort; exclude dollar amounts.",
            "transform": "identity",
        },
        "pell_amount": {
            "target_var": "pell_amount",
            "concept": "Pell Grant dollars",
            "units": "USD",
            "survey": "StudentFinancialAid",
            "period_type": "AY",
            "forms": ["SFA"],
            "label_regex": [
                r"(?:^|.*)\bpell grants?\b.*\b(amount|total|dollars?)\b",
            ],
            "exclude_regex": [
                r"\brecipients?\b|\bavg\b|\baverage\b|\bper[- ]?recipient\b",
            ],
            "notes": "Total Pell dollars; exclude counts and averages.",
            "transform": "identity",
        },

        # Net price (AY, Title IV cohort; SFA historically, CST in recent years)
        "anp_0_30": {
            "target_var": "anp_0_30",
            "concept": "Average net price 0–30k (Title IV)",
            "units": "USD",
            "survey": "SFA",
            "period_type": "AY",
            "forms": ["SFA", "CST"],
            "label_regex": [
                r"average net price.*(?:less than\s*30[, ]?0{3}|0\s*[-–]\s*30[, ]?0{3}|0\s*to\s*30[, ]?0{3}|0\s*-\s*30k)",
            ],
            "exclude_regex": [],
            "notes": "Title IV band.",
            "transform": "identity",
        },
        "anp_30_48": {
            "target_var": "anp_30_48",
            "concept": "Average net price 30–48k (Title IV)",
            "units": "USD",
            "survey": "SFA",
            "period_type": "AY",
            "forms": ["SFA", "CST"],
            "label_regex": [
                r"average net price.*(?:30[, ]?0{3}?\s*(to|[-–])\s*48[, ]?0{3}|30[, ]?001\s*(to|[-–])\s*48[, ]?0{3})",
            ],
            "exclude_regex": [],
            "notes": "",
            "transform": "identity",
        },
        "anp_48_75": {
            "target_var": "anp_48_75",
            "concept": "Average net price 48–75k (Title IV)",
            "units": "USD",
            "survey": "SFA",
            "period_type": "AY",
            "forms": ["SFA", "CST"],
            "label_regex": [
                r"average net price.*(?:48[, ]?0{3}?\s*(to|[-–])\s*75[, ]?0{3}|48[, ]?001\s*(to|[-–])\s*75[, ]?0{3})",
            ],
            "exclude_regex": [],
            "notes": "",
            "transform": "identity",
        },
        "anp_75_110": {
            "target_var": "anp_75_110",
            "concept": "Average net price 75–110k (Title IV)",
            "units": "USD",
            "survey": "SFA",
            "period_type": "AY",
            "forms": ["SFA", "CST"],
            "label_regex": [
                r"average net price.*(?:75[, ]?0{3}?\s*(to|[-–])\s*110[, ]?0{3}|75[, ]?001\s*(to|[-–])\s*110[, ]?0{3})",
            ],
            "exclude_regex": [],
            "notes": "",
            "transform": "identity",
        },
        "anp_110_plus": {
            "target_var": "anp_110_plus",
            "concept": "Average net price 110k+ (Title IV)",
            "units": "USD",
            "survey": "SFA",
            "period_type": "AY",
            "forms": ["SFA", "CST"],
            "label_regex": [
                r"average net price.*(110[, ]?0{3}\s*(or more|\+)|110[, ]?001\s*(or more|\+))",
            ],
            "exclude_regex": [],
            "notes": "",
            "transform": "identity",
        },
    }
)
