"""Concept catalog for label-driven IPEDS harmonization.

This module exposes the ``CONCEPTS`` dictionary used by ``harmonize_new`` to
identify and extract concept-aligned variables from IPEDS survey files. The
catalog replaces CSV crosswalks with an in-repo Python source of truth. Each
concept entry specifies its descriptive metadata, acceptable forms, matching
patterns, and transform hints.

The harmonizer consumes this catalog to drive label-based resolution against the
``dictionary_lake.parquet`` generated by ``01_ingest_dictionaries.py``. When
``download_ipeds.py`` refreshes yearly manifests, ``harmonize_new`` can combine
those manifests with the concept catalog to locate and parse the correct survey
files without editing legacy modules.
"""

from __future__ import annotations

from collections import OrderedDict


CONCEPTS: "OrderedDict[str, dict[str, object]]" = OrderedDict(
    {
        # Finance (FY)
        "total_rev_invest_return": {
            "target_var": "total_rev_invest_return",
            "concept": "Total revenues and investment return (aligned forms)",
            "units": "USD",
            "survey": "Finance",
            "period_type": "FY",
            "forms": ["F1A", "F2A", "F3A"],
            "label_regex": [r"^total revenues? (?:and )?investment return$"],
            "exclude_regex": [],
            "notes": "Use aligned total; do not map to balance-sheet items.",
            "transform": "identity",
        },
        "tuition_fees_net": {
            "target_var": "tuition_fees_net",
            "concept": "Tuition and fees revenue, net of discounts/allowances",
            "units": "USD",
            "survey": "Finance",
            "period_type": "FY",
            "forms": ["F1A", "F2A", "F3A"],
            "label_regex": [
                r"tuition(?: and)? fees.*after deducting (?:discounts|allowances)",
                r"tuition (?:and )?fees.*\(net\)",
            ],
            "exclude_regex": [r"(gross)", r"(before)"],
            "notes": "Avoid double count with scholarships/allowances.",
            "transform": "identity",
        },
        "state_appropriations": {
            "target_var": "state_appropriations",
            "concept": "State appropriations",
            "units": "USD",
            "survey": "Finance",
            "period_type": "FY",
            "forms": ["F1A", "F2A"],
            "label_regex": [r"^state appropriations$"],
            "exclude_regex": [],
            "notes": "Not typically present for for-profits.",
            "transform": "identity",
        },
        "investment_return": {
            "target_var": "investment_return",
            "concept": "Investment return (income, gains, losses)",
            "units": "USD",
            "survey": "Finance",
            "period_type": "FY",
            "forms": ["F1A", "F2A", "F3A"],
            "label_regex": [r"^investment return$", r"^investment (income|return)"],
            "exclude_regex": [],
            "notes": "Flow item; distinct from endowment market value (stock).",
            "transform": "identity",
        },
        "auxiliary_rev": {
            "target_var": "auxiliary_rev",
            "concept": "Auxiliary enterprises revenue",
            "units": "USD",
            "survey": "Finance",
            "period_type": "FY",
            "forms": ["F1A", "F2A", "F3A"],
            "label_regex": [r"^auxiliary (?:enterprise|enterprises) revenues?$"],
            "exclude_regex": [],
            "notes": "Revenue line only.",
            "transform": "identity",
        },
        "total_expenses": {
            "target_var": "total_expenses",
            "concept": "Total expenses (aligned forms)",
            "units": "USD",
            "survey": "Finance",
            "period_type": "FY",
            "forms": ["F1A", "F2A", "F3A"],
            "label_regex": [r"^total expenses?(?: and deductions)?$"],
            "exclude_regex": [],
            "notes": "",
            "transform": "identity",
        },
        "instruction_exp": {
            "target_var": "instruction_exp",
            "concept": "Instruction expenses",
            "units": "USD",
            "survey": "Finance",
            "period_type": "FY",
            "forms": ["F1A", "F2A", "F3A"],
            "label_regex": [r"^instruction$"],
            "exclude_regex": [],
            "notes": "Functional expense.",
            "transform": "identity",
        },
        # Enrollment (AY: EF and E12)
        "ef_total": {
            "target_var": "ef_total",
            "concept": "Total fall headcount",
            "units": "count",
            "survey": "FallEnrollment",
            "period_type": "AY",
            "forms": ["EF"],
            "label_regex": [r"(?:grand )?total(?: students)?$", r"enrollment.*total$"],
            "exclude_regex": [],
            "notes": "EF fall snapshot.",
            "transform": "identity",
        },
        "e12_fte": {
            "target_var": "e12_fte",
            "concept": "12-month FTE (NCES rule)",
            "units": "FTE",
            "survey": "12MonthEnrollment",
            "period_type": "AY",
            "forms": ["E12", "E1D", "EFFY"],
            "label_regex": [r"full[- ]?time equivalent.*"],
            "exclude_regex": [],
            "notes": "Use E12/E1D/EFFY derived FTE.",
            "transform": "identity",
        },
        # SFA (AY)
        "pell_recip_count": {
            "target_var": "pell_recip_count",
            "concept": "Pell Grant recipients (FTFT undergraduates)",
            "units": "count",
            "survey": "StudentFinancialAid",
            "period_type": "AY",
            "forms": ["SFA"],
            "label_regex": [r"pell.*(?:recipients|awarded).*full[- ]?time.*first[- ]?time"],
            "exclude_regex": [],
            "notes": "",
            "transform": "identity",
        },
        "pell_amount": {
            "target_var": "pell_amount",
            "concept": "Pell Grant dollars",
            "units": "USD",
            "survey": "StudentFinancialAid",
            "period_type": "AY",
            "forms": ["SFA"],
            "label_regex": [r"pell grants?.*(?:amount|total)"],
            "exclude_regex": [],
            "notes": "",
            "transform": "identity",
        },
        # Net price (AY, Title IV recipients; pre-2024 SFA; if CST appears, match either)
        "anp_0_30": {
            "target_var": "anp_0_30",
            "concept": "Average net price 0–30k (Title IV)",
            "units": "USD",
            "survey": "SFA",
            "period_type": "AY",
            "forms": ["SFA", "CST"],
            "label_regex": [
                r"average net price.*(?:0[-–]\s?30[, ]?000|0 to 30[, ]?000)",
            ],
            "exclude_regex": [],
            "notes": "Use Title IV band.",
            "transform": "identity",
        },
        "anp_30_48": {
            "target_var": "anp_30_48",
            "concept": "Average net price 30–48k (Title IV)",
            "units": "USD",
            "survey": "SFA",
            "period_type": "AY",
            "forms": ["SFA", "CST"],
            "label_regex": [
                r"average net price.*(?:30[, ]?001[-–]\s?48[, ]?000|30 to 48[, ]?000)",
            ],
            "exclude_regex": [],
            "notes": "",
            "transform": "identity",
        },
        "anp_48_75": {
            "target_var": "anp_48_75",
            "concept": "Average net price 48–75k (Title IV)",
            "units": "USD",
            "survey": "SFA",
            "period_type": "AY",
            "forms": ["SFA", "CST"],
            "label_regex": [
                r"average net price.*(?:48[, ]?001[-–]\s?75[, ]?000|48 to 75[, ]?000)",
            ],
            "exclude_regex": [],
            "notes": "",
            "transform": "identity",
        },
        "anp_75_110": {
            "target_var": "anp_75_110",
            "concept": "Average net price 75–110k (Title IV)",
            "units": "USD",
            "survey": "SFA",
            "period_type": "AY",
            "forms": ["SFA", "CST"],
            "label_regex": [
                r"average net price.*(?:75[, ]?001[-–]\s?110[, ]?000|75 to 110[, ]?000)",
            ],
            "exclude_regex": [],
            "notes": "",
            "transform": "identity",
        },
        "anp_110_plus": {
            "target_var": "anp_110_plus",
            "concept": "Average net price 110k+ (Title IV)",
            "units": "USD",
            "survey": "SFA",
            "period_type": "AY",
            "forms": ["SFA", "CST"],
            "label_regex": [
                r"average net price.*(?:110[, ]?001.*|110[, ]?000 or more|110[, ]?001 or more)",
            ],
            "exclude_regex": [],
            "notes": "",
            "transform": "identity",
        },
    }
)
